apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: dev
spec:
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
        - name: wil
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-service
spec:
  ports:
    port: 8888
    targetPort: 8888
  selector:
    app: wil
